# Workflow to lint LaTeX files with chktex

name: Lint files with chktex

# Triggers the workflow on push or pull request events
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint_file"
  lint_file:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Lint with chktex
        uses: j2kun/chktex-action@1.0.3
